version: '3'

services:
  jupyterhub-gpu-cuda12:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: "0"
    image: jupyterhub-gpu-cuda12
    #shm_size: '64gb'
    #command: generate.py --load_8bit --base_model $BASE_MODEL --lora_weights 'kobkrit/openthaigpt-0.1.0-beta'
    restart: unless-stopped
    volumes:
    #  - openthaigpt-0.1.0-beta:/root/.cache # Location downloaded weights will be stored
       - /home/ubuntu/docker-jupyterhub/data:/home
       - /home/ubuntu/docker-jupyterhub/jupyterhub_config.py:/workspace/jupyterhub_config.py
    ports:
      - 8000:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

volumes:
  jupyterhub-gpu-cuda12:
    name: jupyterhub-gpu-cuda12
